# Generated by Django 4.1.7 on 2023-03-09 16:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230210_1706'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
