# Generated by Django 4.1.7 on 2023-03-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_tags'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='recipe',
            managers=[
            ],
        ),
    ]
